package com.itechart.stockOnline.model.enums;


public enum ProductStatus {

    JOINED, CHEKING_COMPLETED, APPROVED_FOR_STORAGE,
    LOST_CARRIER, LOST_FROM_THE_STOCK, STEALING_FROM_THE_STOCK,
    CARRIER_SHORTAGE, CONFISCATED, RECOVER, OUT_OF_STORAGE, ISSUE_RESOLVED,
    TAKEN_FROM_THE_STOCK
}
