export const FIND_WAYBILL_BY_NUMBER_REQUEST = 'checkGoods/FIND_WAYBILL_BY_ID_REQUEST';
export const FIND_WAYBILL_BY_NUMBER_SUCCESS = 'checkGoods/FIND_WAYBILL_BY_ID_SUCCESS';

export const SHOW_DIALOG = 'checkGoods/SHOW_DIALOG';
export const CLOSE_DIALOG = 'checkGoods/CLOSE_DIALOG';

export const SET_INPUT_VALUE = 'checkGoods/SET_INPUT_VALUE';

export const ACCEPT_WAYBILL_REQUEST = 'checkGoods/ACCEPT_WAYBILL_REQUEST';

export const SET_WAYBILL_VISIBILITY = 'checkGoods/SET_WAYBILL_VISIBILITY';