//Workers
export const GET_WORKERS_SUCCESS = 'GET_WORKERS_SUCCESS';
export const GET_WORKER_SUCCESS = 'GET_WORKER_SUCCESS';
export const DELETE_WORKER_SUCCESS = 'DELETE_WORKER_SUCCESS';
export const POST_WORKER_SUCCESS = 'POST_WORKER_SUCCESS';
