//Workers
export const GET_WORKERS_SUCCESS = 'GET_WORKERS_SUCCESS';
export const GET_WORKERS_UNSUCCESS = 'GET_WORKERS_UNSUCCESS';
export const DELETE_WORKER_SUCCESS = 'DELETE_WORKER_SUCCESS';
export const DELETE_WORKERS_UNSUCCESS = 'DELETE_WORKERS_UNSUCCESS';
export const DELETE_WORKERS_SUCCESS = 'DELETE_WORKERS_SUCCESS';
export const POST_WORKER_SUCCESS = 'POST_WORKER_SUCCESS';
export const CLOSE_WORKERS_RESPONSE = 'CLOSE_WORKERS_RESPONSE';


//Worker
export const GET_WORKER_SUCCESS = 'GET_WORKER_SUCCESS';
export const GET_WORKER_UNSUCCESS = 'GET_WORKER_UNSUCCESS';
export const POST_WORKER_UNSUCCESS = 'POST_WORKER_UNSUCCESS';
export const DELETE_WORKER_UNSUCCESS = 'DELETE_WORKER_UNSUCCESS';
export const CLOSE_WORKER_RESPONSE = 'CLOSE_WORKER_RESPONSE';
//Roles
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_UNSUCCESS = 'GET_ROLES_UNSUCCESS';