export const GET_CLIENT_LIST_REQUEST = 'GET_CLIENT_LIST_REQUEST';
export const GET_CLIENT_LIST_SUCCESS = 'GET_CLIENT_LIST_SUCCESS';

export const SHOW_DIALOG = "SHOW_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";

export const DELETE_CLIENT_LIST_REQUEST = "DELETE_CLIENT_LIST_REQUEST";
export const DELETE_CLIENT_LIST_SUCCESS = "DELETE_CLIENT_LIST_SUCCESS";

export const FORM_CLIENTS_SET_STATUS_RADIO = "FORM_CLIENTS_SET_STATUS_RADIO";
export const SET_FILTER_INPUT_VALUE = "SET_FILTER_INPUT_VALUE";