export const GET_CLIENT_LIST_REQUEST = 'systemClients/GET_CLIENT_LIST_REQUEST';
export const GET_CLIENT_LIST_SUCCESS = 'systemClients/GET_CLIENT_LIST_SUCCESS';

export const SHOW_DIALOG = "systemClients/SHOW_DIALOG";
export const CLOSE_DIALOG = "systemClients/CLOSE_DIALOG";

export const DELETE_CLIENT_LIST_REQUEST = "systemClients/DELETE_CLIENT_LIST_REQUEST";
export const DELETE_CLIENT_LIST_SUCCESS = "systemClients/DELETE_CLIENT_LIST_SUCCESS";

export const FORM_CLIENTS_SET_STATUS_RADIO = "systemClients/FORM_CLIENTS_SET_STATUS_RADIO";
export const SET_FILTER_INPUT_VALUE = "systemClients/SET_FILTER_INPUT_VALUE";

export const SET_FILTER_MESSAGE_VISIBILITY = 'systemClients/SET_FILTER_MESSAGE_VISIBILITY';
export const SET_DEFAULT_STATE = 'systemClients/SET_DEFAULT_STATE';