export const GET_CLIENT_LIST_REQUEST = 'GET_CLIENT_LIST_REQUEST';
export const GET_CLIENT_LIST_SUCCESS = 'GET_CLIENT_LIST_SUCCESS';
export const GET_CLIENT_LIST_FAIL = 'GET_CLIENT_LIST_FAIL';

export const SET_CONFIRM_DELETE_DIALOG_VISIBILITY = "SET_CONFIRM_DELETE_DIALOG_VISIBILITY";

export const SET_NOTHING_TO_DELETE_DIALOG_VISIBILITY = "SET_NOTHING_TO_DELETE_DIALOG_VISIBILITY";