export const ADD_DRIVER_REQUEST = 'ADD_DRIVER_REQUEST';
export const ADD_DRIVER_FAIL = 'ADD_DRIVER_FAIL';
export const ADD_DRIVER_SUCCESS = 'ADD_DRIVER_SUCCESS';

export const GET_DRIVER_REQUEST = 'GET_DRIVER_REQUEST';
export const GET_DRIVER_FAIL = 'GET_DRIVER_FAIL';
export const GET_DRIVER_SUCCESS = 'GET_DRIVER_SUCCESS';

export const SET_FIELD = 'SET_FIELD';
export const SET_INPUT_ERROR_MESSAGE = 'SET_INPUT_ERROR_MESSAGE';

export const SHOW_ALERT_POPUP = 'SHOW_ALERT_POPUP';
export const CLOSE_ALERT_POPUP = 'CLOSE_ALERT_POPUP';

export const SET_DEFAULT_VALUE = 'SET_DEFAULT_VALUE';

export const EDIT_DRIVER_CHANGE_BIRTH_DATE = 'EDIT_DRIVER_CHANGE_BIRTH_DATE';
export const EDIT_DRIVER_CHANGE_PASSPORT_ISSUED_DATE = 'EDIT_DRIVER_CHANGE_PASSPORT_ISSUED_DATE';