export const ADD_CLIENT_REQUEST = 'ADD_CLIENT_REQUEST';
export const ADD_CLIENT_FAIL = 'ADD_CLIENT_FAIL';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';

export const GET_CLIENT_REQUEST = 'GET_CLIENT_REQUEST';
export const GET_CLIENT_FAIL = 'GET_CLIENT_FAIL';
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS';

export const SET_FIELD = 'SET_FIELD';
export const SET_INPUT_ERROR_MESSAGE = 'SET_INPUT_ERROR_MESSAGE';
export const SET_VISIBILITY_PASSWORD = 'SET_VISIBILITY_PASSWORD';

export const SHOW_ALERT_POPUP = 'SHOW_ALERT_POPUP';
export const CLOSE_ALERT_POPUP = 'CLOSE_ALERT_POPUP';

