export const SET_INPUT_ERROR_MESSAGE = 'SET_INPUT_ERROR_MESSAGE';
export const SET_FIELD = 'SET_FIELD';
export const SHOW_ALERT_POPUP = 'SHOW_ALERT_POPUP';
export const CLOSE_ALERT_POPUP = 'CLOSE_ALERT_POPUP';

export const GET_TRAIN_REQUEST = 'GET_TRAIN_REQUEST';
export const GET_TRAIN_FAIL = 'GET_TRAIN_FAIL';
export const GET_TRAIN_SUCCESS = 'GET_TRAIN_SUCCESS';

export const SET_DEFAULT_VALUE = 'SET_DEFAULT_VALUE';

export const ADD_TRANSFER_COMPANY_REQUEST = "ADD_TRANSFER_COMPANY_REQUEST";
export const ADD_TRANSFER_COMPANY_SUCCESS = "ADD_TRANSFER_COMPANY_SUCCESS";
export const ADD_TRANSFER_COMPANY_FAIL = "ADD_TRANSFER_COMPANY_FAIL";
export const EDIT_TRANSFER_COMPANY = "EDIT_TRANSFER_COMPANY";