export const GET_DRIVER_REQUEST = 'GET_DRIVER_REQUEST';
export const GET_DRIVER_FAIL = 'GET_DRIVER_FAIL';
export const GET_DRIVER_SUCCESS = 'GET_DRIVER_SUCCESS';

export const SET_FIELD = 'SET_FIELD';
export const SET_INPUT_ERROR_MESSAGE = 'SET_INPUT_ERROR_MESSAGE';

export const SHOW_ALERT_POPUP = 'SHOW_ALERT_POPUP';
export const CLOSE_ALERT_POPUP = 'CLOSE_ALERT_POPUP';

export const SET_DEFAULT_VALUE = 'SET_DEFAULT_VALUE';

export const ENABLE_NEXT_BUTTON = 'ENABLE_NEXT_BUTTON';
export const DISABLE_NEXT_BUTTON = 'DISABLE_NEXT_BUTTON';