export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const SET_WAYBILL_VISIBILITY = 'SET_WAYBILL_VISIBILITY';
export const SHOW_DIALOG = 'SHOW_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const FIND_WAYBILL_BY_NUMBER_REQUEST = 'FIND_WAYBILL_BY_ID_REQUEST';
export const FIND_WAYBILL_BY_NUMBER_SUCCESS = 'FIND_WAYBILL_BY_ID_SUCCESS';
export const SET_SELECT_SHELF_MODAL_VISIBILITY = 'SET_SELECT_SHELF_MODAL_VISIBILITY';

export const ADD_PRODUCT_ON_PLACE = 'ADD_PRODUCT_ON_PLACE';
export const REMOVE_PRODUCT_FROM_PLACE = 'REMOVE_PRODUCT_FROM_PLACE';
