export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const SET_WAYBILL_VISIBILITY = 'SET_WAYBILL_VISIBILITY';
export const SHOW_DIALOG = 'SHOW_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const FIND_WAYBILL_BY_ID_REQUEST = 'FIND_WAYBILL_BY_ID_REQUEST';
export const FIND_WAYBILL_BY_ID_SUCCESS = 'FIND_WAYBILL_BY_ID_SUCCESS';
