export const ADD_STOCK_REQUEST = 'ADD_STOCK_REQUEST';
export const ADD_STOCK_FAIL = 'ADD_STOCK_FAIL';
export const ADD_STOCK_SUCCESS = 'ADD_STOCK_SUCCESS';

export const GET_STOCK_REQUEST = 'GET_STOCK_REQUEST';
export const GET_STOCK_FAIL = 'GET_STOCK_FAIL';
export const GET_STOCK_SUCCESS = 'GET_STOCK_SUCCESS';

export const SET_FIELD = 'SET_FIELD';
export const SET_INPUT_ERROR_MESSAGE = 'SET_INPUT_ERROR_MESSAGE';

export const SHOW_ALERT_POPUP = 'SHOW_ALERT_POPUP';
export const CLOSE_ALERT_POPUP = 'CLOSE_ALERT_POPUP';

export const SET_DEFAULT_VALUE = 'SET_DEFAULT_VALUE';

export const EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_CHANGE_NUMBER = 'EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_CHANGE_NUMBER';
export const EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_CHANGE_COST = 'EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_CHANGE_COST';
export const EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_CHANGE_STORAGE = 'EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_CHANGE_STORAGE';
export const EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_CLEAR_FIELDS = 'EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_CLEAR_FIELDS';
export const EDIT_STOCK_FORM_DELETE_ROOM = 'EDIT_STOCK_FORM_DELETE_ROOM';
export const EDIT_STOCK_FORM_ADD_ROOM = 'EDIT_STOCK_FORM_ADD_ROOM';
export const EDIT_STOCK_FORM_SELECT_ROOM = 'EDIT_STOCK_FORM_SELECT_ROOM';
export const EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_HIDE = 'EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_HIDE';
export const EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_SHOW = 'EDIT_STOCK_FORM_ADD_ROOM_MODAL_FORM_SHOW';




