export const ADD_STOCK_REQUEST = 'ADD_STOCK_REQUEST';
export const ADD_STOCK_FAIL = 'ADD_STOCK_FAIL';
export const ADD_STOCK_SUCCESS = 'ADD_STOCK_SUCCESS';

export const GET_STOCK_REQUEST = 'GET_STOCK_REQUEST';
export const GET_STOCK_FAIL = 'GET_STOCK_FAIL';
export const GET_STOCK_SUCCESS = 'GET_STOCK_SUCCESS';

export const SET_FIELD = 'SET_FIELD';
export const SET_INPUT_ERROR_MESSAGE = 'SET_INPUT_ERROR_MESSAGE';

export const SHOW_ALERT_POPUP = 'SHOW_ALERT_POPUP';
export const CLOSE_ALERT_POPUP = 'CLOSE_ALERT_POPUP';

export const SET_DEFAULT_VALUE = 'SET_DEFAULT_VALUE';

