export const GET_STOCK_LIST_REQUEST = 'GET_STOCK_LIST_REQUEST';
export const GET_STOCK_LIST_SUCCESS = 'GET_STOCK_LIST_SUCCESS';
export const GET_STOCK_LIST_FAIL = 'GET_STOCK_LIST_FAIL';
export const SHOW_DIALOG = "SHOW_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";
export const DELETE_STOCK_LIST_REQUEST = "DELETE_STOCK_LIST_REQUEST";
export const DELETE_STOCK_LIST_SUCCESS = "DELETE_STOCK_LIST_SUCCESS";
export const DELETE_STOCK_LIST_FAIL = "DELETE_STOCK_LIST_FAIL";