export const GET_STOCK_LIST_REQUEST = 'GET_STOCK_LIST_REQUEST';
export const GET_STOCK_LIST_SUCCESS = 'GET_STOCK_LIST_SUCCESS';

export const SHOW_DIALOG = "SHOW_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";

export const DELETE_STOCK_LIST_REQUEST = "DELETE_STOCK_LIST_REQUEST";
export const DELETE_STOCK_LIST_SUCCESS = "DELETE_STOCK_LIST_SUCCESS";

export const SET_FILTER_INPUT_VALUE = "SET_FILTER_INPUT_VALUE";

export const SET_FILTER_MESSAGE_VISIBILITY = 'SET_FILTER_MESSAGE_VISIBILITY';